[package]
name = "bevy_mod_raycast"
version = "0.4.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Ray Casting for the Bevy Engine."
repository = "https://github.com/aevyrie/bevy_mod_raycast/"
keywords = ["gamedev", "graphics", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]
resolver = "2"

[dependencies]
bevy = { version = "0.8.0-dev", default-features = false, features = [ "render" ] }

[dev-dependencies]
bevy = { version = "0.8.0-dev", default-features = false, features = [
    "bevy_winit",
    "x11",
] }
criterion = "0.3"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }

[[bench]]
name = "ray_mesh_intersection"
harness = false
